# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazykamal < Formula
  desc "Lazydocker-style TUI for Kamal-deployed apps"
  homepage "https://github.com/shuvro/lazykamal"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_darwin_amd64.tar.gz"
      sha256 "37e981d19291bbeb3f8a51a9041aeb7f1c2e3267aa62597cbb4bbf4b05f5d194"

      def install
        bin.install "lazykamal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_darwin_arm64.tar.gz"
      sha256 "4c7cf2d49c3bc414973cae5e1cbd1bddcc8be58599ccd14c8f09febb4868f197"

      def install
        bin.install "lazykamal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_linux_amd64.tar.gz"
      sha256 "986a00528966e7b9687232a42bd92bf3650754bed5a4ed14c4061c385afef2f3"
      def install
        bin.install "lazykamal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_linux_arm64.tar.gz"
      sha256 "605b6db3e5591f31435d2043534d999b5a04ab1ff71ae582446a11ad99f840f6"
      def install
        bin.install "lazykamal"
      end
    end
  end

  test do
    system "#{bin}/lazykamal", "--version"
  end
end
