# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazykamal < Formula
  desc "Lazydocker-style TUI for Kamal-deployed apps"
  homepage "https://github.com/shuvro/lazykamal"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_darwin_amd64.tar.gz"
      sha256 "8206ff5cc518ea35ec1eee294dc725c1fd3b88f727e7ee0bb47a4c667e3e1382"

      def install
        bin.install "lazykamal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_darwin_arm64.tar.gz"
      sha256 "f0116ac0c98ff15943e3b7c60f7e913a297dda3853e48e3eabb0d8e6ffb95772"

      def install
        bin.install "lazykamal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_linux_amd64.tar.gz"
      sha256 "f8fd614478b72e597140e143ecd00e6f54ab214a8b25b2e65c55c7c868a18dd5"
      def install
        bin.install "lazykamal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.1.0/lazykamal_0.1.0_linux_arm64.tar.gz"
      sha256 "4a18eb4659579d0ef07bc7c224a568e67bed7a2f895d98d0d148c2f189c1735e"
      def install
        bin.install "lazykamal"
      end
    end
  end

  test do
    system "#{bin}/lazykamal", "--version"
  end
end
