# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazykamal < Formula
  desc "Lazydocker-style TUI for Kamal-deployed apps"
  homepage "https://github.com/shuvro/lazykamal"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.2.2/lazykamal_0.2.2_darwin_amd64.tar.gz"
      sha256 "015351d550c9842cb9c4a894a83740199699c0799a2f4bb3f3561aaee40f9e53"

      def install
        bin.install "lazykamal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.2.2/lazykamal_0.2.2_darwin_arm64.tar.gz"
      sha256 "c8978e948ee678171c34677e8f9874d4aac48bcfabd52edbeaf5fd5c39da39af"

      def install
        bin.install "lazykamal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.2.2/lazykamal_0.2.2_linux_amd64.tar.gz"
      sha256 "e3529e9a0b8aa4118f2e17df72e241c9eb5bdf6b6bd24bef9c65ad2019d165ff"
      def install
        bin.install "lazykamal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuvro/lazykamal/releases/download/v0.2.2/lazykamal_0.2.2_linux_arm64.tar.gz"
      sha256 "dc9bd570e0a17f552cf97b17bdd339878e70bf8220c2d291b1032586ec7179ba"
      def install
        bin.install "lazykamal"
      end
    end
  end

  test do
    system "#{bin}/lazykamal", "--version"
  end
end
